### ISSUE TITLE
The Dashboard with the Top 10 Performance of all suites and Test case it is overriding with something can you move the Text of Top 10 Performance at top of the Table ?  

### ISSUE THREAD

**Issue by mantrisri** [adiralashiva8/robotframework-metrics#15]
Actual: Chart title "Top 10 Performance" are overlaped with bar graph.
Expected: Show Chart title outside of chart same as Status chart

**Comment by adiralashiva8** [comment]
Commit Message: Show bar chart title outside of chart 
Commit ID: aecd52979dcd039705cd793aaa81db88022bfa20
