### ISSUE TITLE
Disable Email Notification

### ISSUE THREAD

**Issue by Noordsestern** [adiralashiva8/robotframework-metrics#40]
I could not figure out how to disable sending the report in an email. 

I excluded all parts regarding emails from the script. Maybe you could provide a switch for enabling/disabling email notification.

**Comment by adiralashiva8** [comment]
Provided option to disable 'send email' email feature as part of https://github.com/adiralashiva8/robotframework-metrics/commit/67219da1b73a4c9274ac300f6a7b52ec337e8615

**How to disable email**

1. By default robotmetrics.py will send email on executing .py file
2. Using -email false (or) -email False (or) -email 0 can disable send email feature

Example: **python robotmetrics.py -email False**
