### ISSUE TITLE
Externalize Configuration

### ISSUE THREAD

**Issue by Noordsestern** [adiralashiva8/robotframework-metrics#41]
Configuration of the report (i.e. disabling emails, link to report logo) is done in the robotmetrics.py script directly. Which means, you would have to redo all configuration every time a newer version of the script is published.

It would be nice, if the configuration could be done outside the script in a configuration file (properties file, xml, json or anything). That way, you could upgrade the script to a newer version repeating customization.

**Comment by adiralashiva8** [comment]
Its good approach to use property file to configure email and logo. 

But I want to use only one file robotmetrics.py to be downloaded by users and use in project (which need to be included in project). Sometime it's awkward to include multiple files (external 3rd part files) with-in project.

**Comment by Noordsestern** [comment]
I understand.

Maybe the configuration file could be optional. If the configuration file does not exist, the robotmetrics.py uses static default settings the same way it does now. But if somebody provides a configuration file, the settings will be overriden.

That way, you could have both: customization and out-of-the-box working robotframework-metrics.py.

**Comment by adiralashiva8** [comment]
Similar implementation as part of https://github.com/adiralashiva8/robotframework-metrics/pull/52 pull request. Now user have to pass values from command line
