### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by rupakgithub** [adiralashiva8/robotframework-metrics#43]
Traceback (most recent call last):
  File "robotmetrics.py", line 411, in <module>
    kwpp = round(passed_keywords*100.0/total_keywords,2)
ZeroDivisionError: float division by zero

**This error is coming when robot file don't have any keywords but only test cases.**

**Comment by adiralashiva8** [comment]
https://github.com/adiralashiva8/robotframework-metrics/commit/6a37075653820f3c3e2c5e2a3418eec8a96a2b5a
