### ISSUE TITLE
Not able to create robotmetrics report

### ISSUE THREAD

**Issue by mantrisri** [adiralashiva8/robotframework-metrics#46]
Hi Shiva, I have downloaded and copy the python file in my project folder and trying to run python robotmetrics.py but nothing is responding.

Anything to install?
![mertics](https://user-images.githubusercontent.com/25111814/47632903-42667680-db09-11e8-8667-89dcf754c924.PNG)

**Comment by adiralashiva8** [comment]
I was not able to replicate reported case. Could you please share more information like
 - python version
 - robotframework version.

If possible could you please share output.xml for my mail. So that I can debug and fix issue (if any)

**Comment by mantrisri** [comment]
python version=2.7.11
robot framework version=3.0.4

**Comment by adiralashiva8** [comment]
Could you please share your output.XML for debugging issue

**Comment by adiralashiva8** [comment]
I was able to generate report without any errors. Can you re-check folder structure
![image](https://user-images.githubusercontent.com/12430515/47637876-0b34ab80-db83-11e8-8420-8378b77905b4.png)

**Comment by adiralashiva8** [comment]
In older version of python **from __future__ import print_function** is not responding

**Comment by adiralashiva8** [comment]
Fixed as part of commit https://github.com/adiralashiva8/robotframework-metrics/commit/e6f4cced76e2eae5a9848de4e22824723811f81b
