### ISSUE TITLE
calling robotmetrics without any arguments raises an exception

### ISSUE THREAD

**Issue by bkhouri** [adiralashiva8/robotframework-metrics#55]
When calling `robotmetrics` with no arguments, an exception is raised.

```
$ robotmetrics 
Traceback (most recent call last):
  File "/Users/bassam.khouri/venv3/bin/robotmetrics", line 11, in <module>
    sys.exit(main())
  File "/Users/bassam.khouri/venv3/lib/python3.7/site-packages/robotframework_metrics/runner.py", line 102, in main
    generate_report(opts)
  File "/Users/bassam.khouri/venv3/lib/python3.7/site-packages/robotframework_metrics/robotmetrics.py", line 92, in generate_report
    result = ExecutionResult(output_name)
  File "/Users/bassam.khouri/venv3/lib/python3.7/site-packages/robot/result/resultbuilder.py", line 50, in ExecutionResult
    return _single_result(sources[0], options)
  File "/Users/bassam.khouri/venv3/lib/python3.7/site-packages/robot/result/resultbuilder.py", line 75, in _single_result
    raise DataError("Reading XML source '%s' failed: %s" % (unic(ets), error))
robot.errors.DataError: Reading XML source './output.xml' failed: No such file or directory
```

Here is my environment
```
$ python --version
Python 3.7.2

$ robot --version
Robot Framework 3.1 (Python 3.7.2 on darwin)

$ pip freeze | grep robotframework-metrics
robotframework-metrics==3.1.1
```

I'm not familiar with the source code so I don't know what files are required by the tool, but a more human readable error message should be displayed.

**Comment by adiralashiva8** [comment]
We need to call only `robotmetrics` in following situations

1. When output.xml file name is not altered
2. output.xml is in current folder

If above conditions are not met when display exception (Will add human understandble error message in comming releases).

Solution: Pass output.xml path to robotmetrics command

Ex: 

- Your project is in D:/robot and output.xml is in D:/robot/result/output.xml
- User is in D:/robot
- Then command to execute is `robotmetrics -inputpath ./result` this specifies output.xml present location

Please let me know if still issue occurs even after trying above mentioned approach

**Comment by bkhouri** [comment]
I've used the tool and i understand how to use it.  but if the `output.xml` is not specified in the `inputpath` directory, a more appropriate error message should be displayed.

So instead of the exception, display `file <path_to_file> does not exist`.

**Comment by adiralashiva8** [comment]
Agree, will make suggested change in comming release!

**Comment by bkhouri** [comment]
I can submit a PR.  Let me know

**Comment by adiralashiva8** [comment]
Please go ahead and create pull request

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/robotframework-metrics/pull/56 pull requesr
