### ISSUE TITLE
Sending mail via Mailgun API

### ISSUE THREAD

**Issue by plaihonen** [adiralashiva8/robotframework-metrics#58]
It would be nice to be able to use an API such as Mailgun in order to send e-mails.
For instance Mailgun does accept html formatted e-mails, addition to plain text e-mails.

https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api

**Comment by adiralashiva8** [comment]
DEPRECATING send email functionality from 3.1.2, so this enhancement is not required
