### ISSUE TITLE
Report Generation: Improve performance of report generation time

### ISSUE THREAD

**Issue by adiralashiva8** [adiralashiva8/robotframework-metrics#6]
Expected: Improve performance of report generation using  Thread or Multiprocess

**Comment by jz-jess** [comment]
@adiralashiva8 Still need help here?

**Comment by adiralashiva8** [comment]
@jz-jess Yes. I'm facing performance issue while processing big size output.xml files

When output.xml is more than 500mb robotframework-metrics is taking more time (then usual data).

**My XML Data:**

- Suites: > 100
- Tests: > 800
- Keywords: > 2 Lakhs
- Time took to process xml: 80sec
- Time took to load html page: 120sec

**What I'm doing in report:**
I have three class. Which are responsible to capture metrics as follows

- Class 1 - Suite Metrics
- Class 2 - Test Metrics
- Class 3 - Keyword Metrics (more time at here)

I loop for every element in class and add them to data-table.

**What I plan to improve performance:**
I want to run three class in parllel using multipleprocessing from Process

**Comment by adiralashiva8** [comment]
Yes, Other code stuff is to generate html using beautiful soup.
Those three class are independent. Let's have all three class's definition at top and call's need to be in parallel (need to check compatiable)

**Comment by adiralashiva8** [comment]
Implement as part of https://github.com/adiralashiva8/robotframework-metrics/pull/52 using gevent. Will re-open this issue if user concern about performance
