### ISSUE TITLE
process multiple output.xml

### ISSUE THREAD

**Issue by fspegni** [adiralashiva8/robotframework-metrics#63]
Would it be possible to take as input multiple `output.xml` files? Similarly to what `rebot` does. At the moment the only thing I was able to do was to merge the several `output.xml` into a single file (with a single `<robot ...>` element) and pass it to `robotmetrics`. The nasty part is removing the multiple copies of the `<robot ...>` element (one per `output.xml` file), then merge the children elements, then wrap all the children with a single outer `<robot ...>` element. It would be nice if the tool could take care of that.

**Comment by adiralashiva8** [comment]
Workaround for this scenario could be creating .bat or .sh file and execute file (to perfrom multiple actions)
```
robot test.robot &&
rebot --output output.xml --merge output1.xml output2.xml output3.xml &&
robotmetrics [:options]
```
robotframework-metrics will be created by parsing output,xml (which is created by merging multiple xmls)

**Comment by fspegni** [comment]
Digging a bit the robotframework, I found out it already has support for processing multiple output.xml files. So I patched the `robotmetrics.py` file this way:

````
    # output.xml file
    output_names = [ os.path.join(path, curr) for curr in opts.output.split(",") ]

    # report.html file
    report_name = opts.report_name

    # log.html file
    log_name = opts.log_name

##    required_files = (
##        output_name,
##        # report_name,
##        # log_name,
##    )
    required_files = output_names
...
    # Read output.xml file
    result = ExecutionResult(*output_names)

````

I assume the parameter `output` can accept a list of filenames divided by `,`, so I split and append all the names ot the working directory. It seems it works. I test it a little bit more and make a pull request for this, if you agree.

**Comment by adiralashiva8** [comment]
Amazing, I will look into this, thanks for inputs and your contribution

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/robotframework-metrics/pull/65 pull request
