### ISSUE TITLE
Remove send email functionality

### ISSUE THREAD

**Issue by adiralashiva8** [adiralashiva8/robotframework-metrics#66]
Remove send email functionality of robotframework-metrics. As a user I will you other options to send email

**Comment by adiralashiva8** [comment]
Removed functionality as part of this commit https://github.com/adiralashiva8/robotframework-metrics/commit/3cb7a5f156789c0e7f784d105a13c2f71142e712

**Comment by Tset-Noitamotua** [comment]
Why removed email functionality?

**Comment by adiralashiva8** [comment]
> Why removed email functionality?

I have found few issues while using email (specific gmail) and it doesnt work with other email providers, So I have removed this. We can still achieve this requirement using alternative ways
