### ISSUE TITLE
Keyword Metrics may be configurable

### ISSUE THREAD

**Issue by DINESH1990** [adiralashiva8/robotframework-metrics#71]
1) It good if you can make keyword metrics as configurable to the user it will help to improve performance.It is taking long time when we have more test cases.  
2) Its good if the metrics can be accessible from any remote machine, if I share only the metrics.html to anyone.

**Comment by adiralashiva8** [comment]
From `v3.1.6` uses can exclude keywords in report using `--ignorekeywords True`
