### ISSUE TITLE
Encoding error during log generation (character maps to <undefined>)

### ISSUE THREAD

**Issue by bioneyez** [adiralashiva8/robotframework-metrics#78]
Hi!
I'm getting an encoding error during log generation (probably because of cyrillic characters). 
I tried setting the sysdefaultencoding to UTF-8 but it does not work because of python 3+.
![error](https://user-images.githubusercontent.com/13623153/65580381-cf17ef80-df79-11e9-8773-76dcd7ca35c6.PNG)

**Python: 3.7.4**
**robotmetrics: 3.1.4 (pulled from github)**
**OS: Win10**

**Comment by adiralashiva8** [comment]
Could you please share your output.xml to my mail id (go through git profile for mail id) to debug issue

**Comment by bioneyez** [comment]
I've made a dummy test case that produces this error. It seems like it fails on keywords containing UTF8 characters. I sent the output.xml to your email.
