### ISSUE TITLE
(3.1.4) Failed to create metrics-<timestamp>.html file without -M option

### ISSUE THREAD

**Issue by ddhoot09** [adiralashiva8/robotframework-metrics#80]
Issue: Error without -M option
IOError: [Errno 22] invalid mode ('w') or filename: 'C:\\metrics-<timestamp>.html'

Solution:
Do not pass default value to -M option or handle it while fetching args.

**Comment by adiralashiva8** [comment]
Currently 'v3.1.4' is still in development and it can be only installed through command 
```
pip install git+https://github.com/adiralashiva8/robotframework-metrics
```

hope you have installed using above command

**Usage of -M**
Following is usage pattern
```
robotmetrics -M "mycustomname.html"
```
Ex: robotmetrics -M "regression.html"

**Comment by ddhoot09** [comment]
I have just incorporated -M changes locally. But with above commands it is working properly.
Thanks!
