### ISSUE TITLE
Ability to compare runs

### ISSUE THREAD

**Issue by tomaspekarovic** [adiralashiva8/robotframework-metrics#82]
It is any way that I can compare between 2,3,4,'n' runs? (The same runs, the same suites) And get some kind of threshold to find out differences between outputs?

Issue I'm facing is that from time to time I need to compare 2-3-4 runs in between and compare execution time of keywords to find out some of performance issues. This would be great If I can generate report like this.

**Comment by adiralashiva8** [comment]
@tomaspekarovic i feel robotframework-historic will satisfy your requirement

https://github.com/adiralashiva8/robotframework-historic
