### ISSUE TITLE
Support "--name" command 

### ISSUE THREAD

**Issue by lynhbn** [adiralashiva8/robotframework-metrics#83]
Currently I have 3 big xml files:
```
output1.xml
output2.xml
output3.xml
```

After that, I have to use rebot to generate one big report.html & log.html from them: (I need these 2 files for Metrics to display the keyword detail logs)
`/usr/local/bin/rebot --name Regression output1.xml output2.xml output3.xml`

In this step, I use the `--name` command to set the name for the outer suite

Then I will generate the report by the below command:
`robotmetrics --output "output1.xml,output2.xml,output3.xml" --logo "logo/my-logo.png" -l True -s True -k True`

-> In this step, I'm unable to use the `--name` command here, so the outer suite name is always "Suite 1 Name & Suite 2 Name & Suite 3 Name", it's quite long & awkward

Please help to support to customize outer suite name when generating Metrics from multiple output.xml files

**Comment by adiralashiva8** [comment]
I generally dont prefer robotframework-metrics to merge multiple xmls. I split this into two

- use rebot to merge multiple xmls
- use merged xml to generate metrics report

Hope this approach will meet your requirement

**Comment by lynhbn** [comment]
OK, thank you for you reply. I solved the problem with your suggestion.

However, if the robotframework-metrics DO support multiple xml inputs, it should also support the point I suggest above, so we no need any workaround :D 

Best regards
