### ISSUE TITLE
How to take files with timestamp for dashboard?

### ISSUE THREAD

**Issue by Adi-2020** [adiralashiva8/robotframework-metrics#84]
Hi,
Recently I have started using robotframework-metrics 3.1.7 .
I am facing two issues.
1. I  am running my robot script on command line using ` robot --timestampoutputs --log TestLog.html --report TestReport.html --outputdir D:\TestProject_Regression_Screenshots\TestAutomationResult -T TesttTestSuite_5Oct`  My output/report/log files are saving with the timestamp like _**output-10102020.xml, log-10102020.html**_ but robotmetrics is asking for just output/log file so how to manage that?
2. I am developing test scripts in eclipse and I have 50 test scripts in 50 .robot files. Now when I run robotmetrics it is showing me same number for test suite and test script ie 50. Ideally it should 1 test suite as all the test scripts are in one folder and 50 test cases. Is there any suggestion to carry out it?
Thanks.

**Comment by adiralashiva8** [comment]
**Query 1**: By default robotframework-metrics use `output.xml` this can be override by following command
```
robotmetrics --inputpath "D:\TestProject_Regression_Screenshots\TestAutomationResult" --output output-10102020.xml --log log-10102020.html
```
or
```
# open command line to location D:\TestProject_Regression_Screenshots\TestAutomationResult then use following command
robotmetrics --output output-10102020.xml --log log-10102020.html
```

We need to specify file name to robotmetrics (may be limitation). Generally i will avoid using `--timestampoutputs`

Reference (step 2):  https://github.com/adiralashiva8/robotframework-metrics#how-to-use-in-project

**Query 2**: Try including full suite name

```
robotmetrics -s True --output output1.xml --log log1.html
```
Refernce: https://github.com/adiralashiva8/robotframework-metrics#include-full-suite-name-in-metrics-report

**Comment by Adi-2020** [comment]
Thanks will try implementing the mentioned changes.
