### ISSUE TITLE
HTML in Test Message not considered

### ISSUE THREAD

**Issue by franky1964** [adiralashiva8/robotframework-metrics#85]
RF has an option to set/add the content of the test message by using HTML syntax:

Run Keyword If    '${TEST STATUS}' == 'FAIL'     Set Test Message    *HTML*<br>${htmlReport}    true

Result:
*HTML*<a href="../requests/requestReportExtra_1602492319038.html" style="color:green;">Request Details (Read All Employees)</a></br>

Problem:
In "Test Metrics" table the column "Error Message" should be renamed to "Test Message" and the content should be displayed 
supporting HTML syntax (see please Test Report, there the above link is displayed" c
![Error_Message](https://user-images.githubusercontent.com/58699432/95727148-1a329c80-0c7a-11eb-9dce-f08217014dba.png)
orrectly.

**Comment by adiralashiva8** [comment]
Thanks for reporting issue, Will fix this issue ASAP probably in next release (within week)

**Comment by adiralashiva8** [comment]
Fixed as part of `v3.2.0` release
