### ISSUE TITLE
Missing column "Tags" in table "Test Metrics"

### ISSUE THREAD

**Issue by franky1964** [adiralashiva8/robotframework-metrics#86]
After update to version v3.2.0 the column disappeared...
![Table_Test_Metrics_v3 2 0](https://user-images.githubusercontent.com/58699432/97903031-b95d2800-1d3e-11eb-855a-1e1899d7a866.png)

**Comment by adiralashiva8** [comment]
Due to limited space made tag to show on demand

```
'-t', '--showtags',
default="False",
```

Users can enable tags using above option like `robotmetrics -t True`

**Comment by franky1964** [comment]
Ok, this new option does solve my issue.
Thank you for this quick answer!
