### ISSUE TITLE
Modify RFmetrics tests Graph according output.xml's tag

### ISSUE THREAD

**Issue by heenaparmar1** [adiralashiva8/robotframework-metrics#87]
Hi,
I want to modify RF-metrics, to get tests graph according to tag of output.xml. Is it possible? If yes could you please guide me?

Thanks,
Heena

**Comment by adiralashiva8** [comment]
Requested feature is not possible with current implementation of robotframework-metrics

But this could be good feature to add in robotframework-historic report - https://github.com/adiralashiva8/robotframework-historic

I will look into possibilities in historic report

**Comment by heenaparmar1** [comment]
ok thank you
one more question i have,  I try to modify the robotmetrix.py its not reflated in the graph (matrix output). Is it possible ? if possible could you please guide me ? 

Thanks ,
Heena

**Comment by adiralashiva8** [comment]
Clone project and changes in python file and install the changes. Use following command in root folder
`python setup.py install`

In future if you make any changes, upgrade version and install so changes will be reflected

**Comment by heenaparmar1** [comment]
To install the change i used below command 
 python3 setup.py install

After that i run robotmetrix and created the output but what ever the change i made its not  reflected in output file.
which command u are using for upgrade the version ?
  
Thanks,
Heena

**Comment by adiralashiva8** [comment]
Step 1: Uninstall robotframework-metrics

Step 2: Update version in version.py file https://github.com/adiralashiva8/robotframework-metrics/blob/master/robotframework_metrics/version.py

Step 3: Install changes

If need any help in installation steps we can google (like python local library installation)

**Comment by heenaparmar1** [comment]
this things also i tried but its not working.

**Comment by adiralashiva8** [comment]
Please send out an email, will schedule call tomorrow if its mandatory

**Comment by heenaparmar1** [comment]
yes sure
