### ISSUE TITLE
the --email tag is not recognized

### ISSUE THREAD

**Issue by lachan-leela** [adiralashiva8/robotframework-metrics#89]
**When I run the following command from cli as per the official documentation:**
robotmetrics --email true --from "emailaddress1@gmail.com" --pwd "secret_password" --to "emailaddress2@gmail.com" --cc "emailaddress3@gmail.com" 

**I encounter the following error:**
usage: 
robotmetrics [-h] [-v] [--logo LOGO] [--ignorelib IGNORE [IGNORE ...]] [--ignoretype IGNORETYPE [IGNORETYPE ...]]
                    [-I PATH] [-M METRICS_REPORT_NAME] [-R REPORT_NAME] [-L LOG_NAME] [-O OUTPUT] [-k IGNOREKEYWORDS]
                    [-l IGNORELOGS] [-s FULLSUITENAME] [-t SHOWTAGS]
robotmetrics: error: unrecognized arguments: --email true --from emailaddress1@gmail.com --pwd secret_password --to emailaddress2@gmail.com --cc emailaddress3@gmail.com

**Comment by adiralashiva8** [comment]
Email functionality deprecated (removed) long back, please use external tools to send metric report
