### ISSUE TITLE
Fails when the xml contains multibyte chars

### ISSUE THREAD

**Issue by amitlohar** [adiralashiva8/robotframework-metrics#92]
So our output.xml contains multibyte chars like "平^~ŸÁ&", which I think robotmetrics is unable to parse. It fails to create the log and we have some python error on command line.

![image](https://user-images.githubusercontent.com/16451046/127974251-1d894ae4-676e-49bd-a1f6-110769fc1ef3.png)

**Comment by amitlohar** [comment]
I was able to fix this issue on my local by making following changes to `robotmetrics.py`

    # Write output as html file
    with open(result_file, 'wb') as outfile:
        outfile.write(soup.prettify().encode("UTF-16"))

Here UTF-8 should also work, but I haven't tested it yet

**Comment by adiralashiva8** [comment]
This should be fixed in v3.3.1 version, could you please confirm

**Comment by amitlohar** [comment]
@adiralashiva8  I tested the newer version but failed with same unicode error.

<img width="800" height="300" alt="unicode_error" src="https://user-images.githubusercontent.com/16451046/149931590-be01b17d-9b7e-4c09-8212-6ff6a8833bff.PNG">

After lot of debugging, I could fix this issue using `codecs`. The required code change in `robotmetrics.py` is:

```
import codecs

logging.info(" Writing results to html file")
    #with open(result_file_name, 'w') as fh:
    with codecs.open(result_file_name,'w','utf-8') as fh:
        fh.write(template.render(
            hide_tags = hide_tags,
            # hide_keyword_menu = hide_keyword_menu,
            hide_kw_times_menu = hide_kw_times_menu,
            suite_stats = suite_stats,
            test_stats = test_stats,
            kw_stats = kw_stats,
            suites = suite_list,
            tests = test_list,
            # keywords = kw_list,
            keyword_times = kw_times,
            error_stats = error_stats,
            suite_error_stats = suite_error_stats,
        ))
```

**Comment by adiralashiva8** [comment]
Thank you @amitlohar , i will push the suggested changes in hour

**Comment by adiralashiva8** [comment]
@amitlohar could you please try now with `3.3.2` version. https://pypi.org/project/robotframework-metrics/3.3.2/

**Comment by amitlohar** [comment]
Tested on `3.3.2` works fine.

**Comment by adiralashiva8** [comment]
Thanks a lot, closing issue
